### ISSUE TITLE
Feature request:  random re-spawn rates

### ISSUE THREAD

**Issue by irobot73** [Anabella00geek/7D2D-Vehicle-Respawner-A20#1]
Not being a modder myself, is it possible to tweak your current MOD to, say, respawn wrecks/shells faster than the Mo' Power trucks?

Maybe able to utilize the 'LootRespawnDays' from the CFG?  IE:  LRD = 20, wrecks @ 1.5 (up to 30 days to respawn), MoPower @ 2.75 (up to ~47 days), Bus @ 4 (80 days)

Love the MOD & apprec. the work

**Comment by Anabella00geek** [comment]
Thanks for the comment. It would not be something I could do. That setting in the config is only to set how many days for everything.  There is not a way to make it random.

**Comment by irobot73** [comment]
I meant reading FROM the cfg, making the re-spawn time for the vehicles random.  Sorry if I wasn't clear.
